{\rtf1\ansi\ansicpg936\cocoartf1504\cocoasubrtf830
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fnil\fcharset134 PingFangSC-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green200\blue50;\red255\green0\blue50;}
{\*\expandedcolortbl;;\csgenericrgb\c0\c78431\c19608;\csgenericrgb\c100000\c0\c19608;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 spring:\cf0 \
  \cf2 profiles:\cf0 \
    \cf2 active:\cf0 \
    - dev\
---\
\cf2 spring:\cf0 \
  \cf2 profiles:\cf0  dev \cf3 #
\f1 \'bf\'aa\'b7\'a2\'bb\'b7\'be\'b3
\f0 \cf0 \
  \cf2 application:\cf0 \
    \cf2 name:\cf0  microservicecloud-config-jackz-dev\
---\
\cf2 spring:\cf0 \
  \cf2 profiles:\cf0  test\
  \cf2 application:\cf0 \
    \cf2 name:\cf0  microservicecloud-config-jackz-test}